[package]
name = "some_rust_lib"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
lean-sys = { version = "0.0.5", features=["small_allocator"], default-features=false }
oxrdf = "^0.2.0-alpha.2"
oxrdfio = "0.1.0-alpha.2"
