[package]
name = "some_rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
json = "0.12.4"
lean-sys = { version = "0.0.5", features=["small_allocator"], default-features=false }
oxrdf = "=0.2.3"
oxrdfio = "=0.1.3"
